export const ADD_TO_CART = "ADD_TO_CART";
export const CART_PRODUCTS_COUNT = "CART_PRODUCTS_COUNT";
export const INCREASE_ITEMS_IN_CART = "INCREASE_ITEMS_IN_CART";
export const DECREASE_ITEMS_IN_CART = "DECREASE_ITEMS_IN_CART";
export const DELETE_ITEMS_FROM_CART = "DELETE_ITEMS_FROM_CART";
export const GET_PRODUCTS = "GET_PRODUCTS";
